###  @name authenticate
POST http://localhost:3333/auth
Content-Type: application/json

{
    "email": "neto.esposito@gmail.com",
    "password": "1234"
}

###  @name register
GET http://localhost:3333/borrowings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNTEwYWNiMC03ZWVmLTRhZTgtYTlmZS1lODcxZGEzZTRiN2YiLCJpYXQiOjE3MzQ1NTg1MTQsImV4cCI6MTczNDU2ODUxNH0.wemqTMIfFTXF024UWItawPNeF07RGZL_8SkyQkeom_E
###  @name return
POST http://localhost:3333/borrowings/return
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNTEwYWNiMC03ZWVmLTRhZTgtYTlmZS1lODcxZGEzZTRiN2YiLCJpYXQiOjE3MzQ1NTg1MTQsImV4cCI6MTczNDU2ODUxNH0.wemqTMIfFTXF024UWItawPNeF07RGZL_8SkyQkeom_E

{
    "id": "70e513d2-2cb1-469b-95f5-22ab5fc6e54b"
}
