version: '3.8'

services:
  postgres:
    container_name: library-manager   
    image: postgres:17.1-alpine3.20
    networks:
      - library-manager-app
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: library-manager    
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: library-manager-api  
    depends_on:
      - postgres
    networks:
      - library-manager-app
    ports:
    - 3333:3333
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    develop:
      watch:
        - path: ./src
          target: /usr/src/app
          action: sync  
        - path: ./src  
          target: /usr/src/app
          action: rebuild
networks:
  library-manager-app:
    driver: bridge

volumes:
  data: